travis:
  secure:
    BINSTAR_TOKEN: F08Z5UiRpNq9Ng6gLdL9VR+TI/K3fHDg0Hv/soyvIkt+Jr1KlAY0wYW0+catEob8N+RBjltv6Fmx+L8ZwMm5JZjJToW/OlzZt5O3ivcdpExUZsy2qcah9sQrDcWpnxEDDP6tcdcYr8z1X60ca8M1Wkf/PIhNRxUv1Ojg9zshBGRE8Rk2rHwa1xHmzyde6VNGMczL6pL1eAHR0Yzs04cwMQlJtwltU/2VnqVN+4HD3e0OUDGFAqgw5B9j/aGTb+IkJ90NU6WYoyk8E3IBXcidh+RKnSXdG440L+U14thouX8VmYFrNnPvN75bpp+MEd/jawtE6peT0xbgqHCv7sRN0X0wNgYniMmeWpPYNijPDfPJN+hQAk4SCxV1aecYksVDFYcnUiPX/FJdriMViAG7JjXw5htZApbHvyt1KUKOVRbPIJqSmNi/DIbwJ9Bi1ZxqADfJZ8rCgm1/0M8FIs9JrET4GmoITasgdUs8/ynMcPeg2ErkFnq8ia+FcunGv0x9Ns+9b2Mn6sXG8DX9DVhNMCSQuUuQm7JMhVDqh4vmpG05AY42f57mSn/P2MVVeFKHUy1HStR7ymLF9TWKASSF9TW3hMlSBfwPPIMpQPZE5Qfa3W1jg4zno4tLwg3LTxYJCftQGRUgZNK2Aj7Kawfuz7VLbmbZzIoqEA32u3DCjQU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
