travis:
  secure:
    BINSTAR_TOKEN: AgQsp4ysXg7uOYyw2mP0chMVrqUVCI877rhoTMugIEtAwG7xuZUED6P+r7kodKcl6Jojj7FlZ2St96ANSKJHUKW+B42Xqc/GeYPvzG8EuJejm4udsvAXW5r2acsEjgq5j9Uc1ECVFpahdgB24BItvQoCVLjOn8WXaOgFeHAyXegRRj77/RHLD0ZV0JXH/CkKrgSXg1t5gWvrbQhc7ZkJxyPhfMmuw//9ZP+q9Ay/ZkM9gixiz+OuyPMj2mHRFroCCqfKUn0Esx0VJQOtAb1nrKhdXsCYqOPSBWqKx/4oIra+1f2ljnoZTi7P8iuTHKc3lCeb+FKbM/flbVAJvf6gwl2SJWJcfh05YPN2q72Q16Dg7v+FuqxFDmJXJlp8PH6L9BsIAqWBG8LnfYwInMtOVlrIcVqmJNbn0+bjUelStOxLJKn6RGckDXaqle4TxfFmpk1FNdalT50S8fAdvGI/zIJEsfklu/2dBhctgjR5vXGJbGZCo4p5WOCzeRdt5u83wUnly4IkVpZ+0kuBoyQhbWgauLVFd/5rcDbbJBudggeg1Hrw5hVNWYfzRWm2GEiEJjpm3pEZFxwrEw9CdSMcVIvvwYoViHVQVI1iU4yc/A0P5Xbh8eeZ/1pvgvdG7EBQ5I19Q2XLWYIVGnRWL6RPzJKrxx3QoM9aVe9vrXrqkTs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
